Proyecto para prueba de Doxygen: funciones_cripto.h File Reference
funciones_cripto.h File Reference
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado de Ingeniería Informática Informática Básica.
#include <string>
Functions
void Parametros (int argc, char *argv[])
Controla que los parámetros que se le pasan a la funcion main sean correctos.
std::string EncriptXor (std::string cadena_a_encriptar, std::string palabra_clave)
Encripta o desencripta el mensaje que se le pasa por parámetro.
std::string EncriptCesar (std::string cadena_a_encriptar, int k_encriptar)
Encripta o desencripta el mensaje que se le pasa por parámetro.
bool EsEntero (std::string cadena)
Comprueba si la string es un número entero.
Detailed Description
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado de Ingeniería Informática Informática Básica.
Author
Iván Texenery Díaz García
Date
12/12/2020 Declaraciones de funciones del programa principal.
Definition in file funciones_cripto.h.
Function Documentation
EncriptCesar()
std::string EncriptCesar (std::string cadena_a_encriptar, int k_encriptar)
Encripta o desencripta el mensaje que se le pasa por parámetro.
Parameters
Mensaje a encriptar mediante encriptado cesar y valor de k para cifrar el mensaje.
Returns
Mensaje inicial encriptado.
Definition at line 68 of file funciones_cripto.cc.
Referenced by main().
{
   for(size_t i = 0; i < cadena_a_encriptar.length(); ++i){
     cadena_a_encriptar[i] += k_encriptar;
   }
   return cadena_a_encriptar;
 }
EncriptXor()
std::string EncriptXor (std::string cadena_a_encriptar, std::string palabra_clave)
Encripta o desencripta el mensaje que se le pasa por parámetro.
Parameters
Mensaje a encriptar mediante xor y palabra clave para cifrar el mensaje.
Returns
Mensaje inicial encriptado.
Definition at line 50 of file funciones_cripto.cc.
Referenced by main().
{
   std::string cadena_encriptada{""};
   std::string clave_encriptada{""};
   for(size_t i = 0; i < palabra_clave.length(); ++i){
     clave_encriptada.push_back(palabra_clave[i] ^ (char)128);
   }
   for(size_t i = 0; i < cadena_a_encriptar.length(); ++i){
     cadena_encriptada.push_back(cadena_a_encriptar[i] ^ clave_encriptada[i % clave_encriptada.length()]);
   }
   return cadena_encriptada;
 }
EsEntero()
bool EsEntero (std::string cadena)
Comprueba si la string es un número entero.
Parameters
Cadena para comprobar si es un entero.
Returns
False o True dependiendo de si es un entero o no.
Definition at line 80 of file funciones_cripto.cc.
Referenced by main().
{
   for(auto elemento: cadena)
   {
     if(elemento < 48 || elemento > 57)
       return false;
   }
   return true;
 }
Parametros()
void Parametros (int argc, char * argv[])
Controla que los parámetros que se le pasan a la funcion main sean correctos.
Parameters
Cantidad de parámetros introducidos, array de caracteres con los argumentos introducidos.
Definition at line 21 of file funciones_cripto.cc.
Referenced by main().
{
   const std::string kTextoAyuda = "  Modo de uso: ./cripto fichero_entrada fichero_salida método password operación\n\
   fichero_entrada: Fichero a codificar\n\
   fichero_salida:  Fichero codificado\n\
   método:          Indica el método de encriptado\n\
                    1: Cifrado xor(introducir 'xor')\n\
                    2: Cifrado de César(introducir 'cesar') \n\
   password:        Palabra secreta en el caso de método 1, Valor de K en el método 2\n\
   operación:       Operación a realizar en el fichero\n\
                    +: encriptar el fichero\n\
                    -: desencriptar el fichero";
   std::string parametro{argv[1]};
   if (parametro == "--help") {
     std::cout << kTextoAyuda << std::endl;
     exit(EXIT_SUCCESS);
   }
   if (argc != 6) {
     std::cout << argv[0] << " Modo de uso: ./cripto fichero_entrada fichero_salida método password operación" << std::endl;
     std::cout << "Pruebe " << argv[0] << " --help para más información" << std::endl;
     exit(EXIT_SUCCESS);
   }
 }